{{- if .Values.expenseFrontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dentacrm.fullname" . }}-expense-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dentacrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: expense-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.expenseFrontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "dentacrm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: expense-frontend
{{- end }}
